### ISSUE TITLE
Resolution issue?

### ISSUE THREAD

**Issue by rgm-22** [o0olele/UVCcamera-Opencv#1]
**Great work! Thank you!** 

I would like to modify the libraries because I am having this excepition:

I/AbsUVCCameraHandler: **supportedSize**:{"formats":[{"index":1,"type":4,"default":1,"size":["160x120"]},{"index":2,"type":4,"default":1,"size":["160x120","160x122"]},{"index":3,"type":4,"default":1,"size":["160x120"]},{"index":4,"type":4,"default":1,"size":["160x120"]},{"index":5,"type":4,"default":1,"size":["160x120"]}]}
V/zhf_debug: handleSetPreviewCallback: frameCallback=com.example.o0orick.camera.MainActivity$5@d9370d9
I/libUVCCamera: [14743*UVCPreview.cpp:266:callbackPixelFormatChanged]:PIXEL_FORMAT_RGB565:
V/CameraThread: handleStartPreview:
W/System.err: java.lang.IllegalArgumentException: Failed to set preview size
W/System.err:     at com.serenegiant.usb.UVCCamera.**setPreviewSize**(UVCCamera.java:328)

With these values:

**private static final int PREVIEW_WIDTH = 160; 
private static final int PREVIEW_HEIGHT = 120;
private static final int PREVIEW_MODE = 0; // YUV**

My camera has the following features:

- 160 x 120
- 9 fps
- UYVY format

Any suggestion to solve it or build the libraries?

Thank you very much in advance!

**Comment by o0olele** [comment]
Still have this problem?

If you want to try build the library youself, turn to the [saki4510t/UVCCamera](https://github.com/saki4510t/UVCCamera)

**Comment by rgm-22** [comment]
Thanks for your answer o0olele!

Yes, but I'll get it ;) (I hope...)
After a long time...now, I can build the library ([saki4510t / UVCCamera](https://github.com/saki4510t/UVCCamera)).
I am going to integrate OpenCV thanks to your project. I have seen that perhaps it is a good idea for a clean result to generate .aar files ;)

Thank you very much!
