### ISSUE TITLE
Library code

### ISSUE THREAD

**Issue by rgm-22** [o0olele/UVCcamera-Opencv#2]
Great work o0olele! Thank you!

Please, could you share your "libuvccamera.aar" code for a more comfortable developing?

Thank you in advance :)

**Comment by o0olele** [comment]
[here](https://github.com/saki4510t/UVCCamera)

**Comment by rgm-22** [comment]
Thank you o0olele!

I've already known saki4510 camera. I am working with it. That is why I need the library code not the release compiled aar files to make my own library changes.

Because I am quite sure that saki4510  made some changes to integrate the OpenCV library.

Any help is really appreciate o0olele! :)
